/**
 * `chowa init` scaffolding
 *
 * Writes a minimal, working `chowa.config.js` derived from the built-in
 * `DEFAULT_POLICY`. Kept as a pure planning module — the actual file write
 * happens in `cli.ts`'s handler — mirroring the `planInstall` split already
 * used in `src/integrations/install.ts`.
 */

import { join } from 'node:path';

import { DEFAULT_POLICY, findConfigPath } from '../router/loadPolicy.js';

export class ConfigAlreadyExistsError extends Error {
  constructor(public readonly existingPath: string) {
    super(
      `A Chōwa config already exists at "${existingPath}" — "chowa init" ` +
        `won't overwrite it. Edit it directly, or delete it first to start over.`,
    );
    this.name = 'ConfigAlreadyExistsError';
  }
}

export interface InitPlan {
  readonly targetPath: string;
}

/**
 * Decide where `chowa init` would write, without touching the filesystem.
 * Refuses (via `ConfigAlreadyExistsError`) if any `CONFIG_CANDIDATES` file
 * is already present — reuses `findConfigPath` rather than re-probing the
 * candidate list itself.
 */
export function planInit(cwd: string = process.cwd()): InitPlan {
  const existing = findConfigPath(cwd);
  if (existing) {
    throw new ConfigAlreadyExistsError(existing);
  }
  return { targetPath: join(cwd, 'chowa.config.js') };
}

/**
 * Starter `chowa.config.js` contents: `DEFAULT_POLICY` rendered as the
 * `routing` field of a `ChowaConfig` module. `DEFAULT_POLICY` has no
 * function fields, so a plain `JSON.stringify` round-trips through
 * `loadPolicy()` unchanged.
 */
export function defaultConfigFileContents(): string {
  const routing = JSON.stringify(DEFAULT_POLICY, null, 2);

  return `/**
 * Chōwa routing policy — generated by \`chowa init\` from the built-in
 * default. Edit the rules below, or replace them entirely; see README.md
 * for the config shape (routing.rules[] + routing.defaultTarget).
 */

const config = {
  routing: ${routing},
};

export default config;
`;
}
